### PR TITLE
Funder database integrations

### PR DESCRIPTION
**Pull request by anusharanganathan**
This is a PR for https://github.com/antleaf/jct-project/issues/468

The import functions are working `API.service.jct.import_funder_config()` and `API.service.jct.import_funder_language()` 

The new URL endpoints are not working for me. They seem to do nothing. Can you please check that.
- service/jct/funder_config
- service/jct/funder_config/import
- service/jct/funder_language
- service/jct/funder_language/import

**NOTE** You would need to init the submodule

### CODE REVIEW

**Comment by markmacgillivray** [comment]
Are none of the new URLs working? I'd guess that the ones where you are using a timeout are not working because the wrapped method that you call only states the function name, it doesn't execute them. e.g. on line 159

Meteor.setTimeout (() => API.service.jct.import_funder_config), 1

probably needs to be 

Meteor.setTimeout (() => API.service.jct.import_funder_config()), 1

**Comment by anusharanganathan** [comment]
No just the ones I added are not working

**Comment by markmacgillivray** [comment]
For the import ones, line 159 and 167, my suggestion in the last comment will probably fix it.

For the other two, which call search endpoints, they look like they should work. I'll investigate further.

**Comment by markmacgillivray** [comment]
Yep, the two search endpoints you created should work, they're the same code structure as other working search endpoints already declared in there.

**Comment by markmacgillivray** [comment]
If the search endpoints you created don't work, I'm not sure why that would be. Could Steve check the index (or check locally yourself if you're running a local ES) to see if they got created? Whenever the code restarts it should automatically create new indexes that you declared, so I would think it did.

**Comment by anusharanganathan** [comment]
Thanks Mark. I will check again if my search endpoints are not working. I will modify the two lines you suggested for the import and test again.

**Comment by anusharanganathan** [comment]
The imports and search work

**Pull request merged**
